[package]
version = "0.1.5"
authors = ["Omniverse GenAI Team"]
title = "AIQ Chat USD Agent"
description = "Integration of Chat USD Agent capabilities for AIQ"
readme = "docs/README.md"
repository = ""
category = "Internal"
keywords = ["ai", "LangChain", "USD", "AIQ"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.ai.chat_usd.bundle" = {}
"omni.ai.langchain.aiq" = {}
"omni.ai.langchain.extra" = { optional = true }

[[python.module]]
name = "omni.ai.aiq.agent.chat_usd"

[fswatcher.patterns]
include = ["*.toml", "*.py", "*.md"]

[settings.exts."omni.ai.aiq.agent.chat_usd"]
# Extension settings can be added here

[package.writeTarget]
kit = true
python = true
usd = true

[documentation]
pages = [
    "docs/README.md",
    "docs/CHANGELOG.md"
]

[[test]]
stdoutFailPatterns.exclude = [
    "*Warning:*",
]
